[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm ci",
  "npm --prefix server install",
  "npm --prefix client install"
]

[phases.build]
cmds = [
  "npm --prefix client run build",
  "node scripts/prepare-static.js"
]

[start]
cmd = "npm start"
